#!/usr/bin/env bash
# Bash that installs NGINX on server

apt-get update
apt-get -y install nginx
echo "Holberton School for the win!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx start
